---
title: "Stat 380 Project"
author: "Ann DeFrancesco, Adam Whiteside, Madeleine Willson"
toc: true
title-block-banner: true
title-block-style: default
format: pdf
editor: 
  markdown: 
    wrap: 72
---



```{r}
#load packages
library(ggplot2)
library(readr)
library(tidyverse)
```

```{r}
#load and read our csv file
flightdelay <- read.csv("~/Downloads/full_data_flightdelay.csv")
head(flightdelay)
```

```{r}
#preliminary data cleaning
flightdelay <- flightdelay %>%
  rename_all(tolower) %>% 
  na.omit() %>% 
  select(month, day_of_week, dep_del15, dep_time_blk, distance_group, segment_number, carrier_name, departing_airport, previous_airport, prcp, snow, tmax, awnd) %>% 
  rename(delay = dep_del15, dep_time = dep_time_blk, distance = distance_group, trip_segment = segment_number, airline = carrier_name, precipitation = prcp, max_temp = tmax, wind = awnd) 
  

head(flightdelay)
summary(flightdelay)
```

Visualizations
```{r}
ggplot(data = flightdelay, aes(x = MONTH, y = AIRPORT_FLIGHTS_MONTH)) +
  geom_point()
```


